# Generated by Django 3.2.7 on 2021-09-26 06:26

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('message', models.CharField(max_length=1000)),
                ('count', models.IntegerField()),
                ('contact_no', models.CharField(max_length=100)),
            ],
        ),
    ]
