# Generated by Django 3.2.7 on 2021-09-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('sms_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='smslogmodel',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
