# Generated by Django 3.2.7 on 2021-09-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0002_auto_20210926_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslogmodel',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
    ]
