# Generated by Django 3.2.7 on 2021-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_consumer', '0003_alter_smslogmodel_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsuser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
